# Generated by Django 6.0.2 on 2026-02-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
    ]
