# Generated by Django 6.0.2 on 2026-03-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgrade',
            options={'ordering': ['level']},
        ),
        migrations.AddField(
            model_name='classgrade',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
